jobs:
  build:
    name: Build Plugins
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Verify Java Version
        run: java -version

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and save errors only
        run: |
          chmod +x gradlew
          echo "JAVA_HOME is $JAVA_HOME"
          ./gradlew make --no-daemon --stacktrace --info 2> gradle-error.log
          
          if [ -s gradle-error.log ]; then
            echo "Gradle errors detected:"
            cat gradle-error.log
          else
            echo "No errors detected."
          fi

      - name: Upload plugin artifacts
        if: success()
        uses: actions/upload-artifact@v6
        with:
          name: plugins
          if-no-files-found: error
          path: ${{ github.workspace }}/plugins/**/build/outputs/*.zip
